<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>username_required</name>
   <tag></tag>
   <elementGuidId>c0c9bcb4-d400-4cca-9896-c65a9936448f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/ol/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listitem</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1b05a12d-2696-497a-ba59-b92dded72f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>218f5931-0b3a-43d8-bb67-61cdf8a66e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rich-colors</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6711a3a9-0347-473a-93b5-36ccbb4ab65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-styled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>50393e2c-a425-4ab5-9343-f0a889f0a8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mounted</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06b65d59-ff1b-4daf-a157-be0aa3a38ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promise</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8298849d-39c5-42eb-8679-4a68330acb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swiped</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5f415d1-a0ae-48d9-b628-87a1175f9bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-removed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1ac7603-d643-4afa-9f16-f62dc249f0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0d6c637-a271-460f-8b19-7ee6e1760b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-y-position</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>f969ebd6-3bd3-4eb2-98f5-0954cea59e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-x-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>d20843e0-6252-4577-97fa-f01cf44f8f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cf2c66c-0579-42bf-9fec-5d00d9ccb414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-front</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29cbbfaa-6729-49fa-9800-a12a70d95ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swiping</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec53cf1b-bd13-430a-b6e7-50f1e5b4a0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismissible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ceb44703-41b6-4c33-b729-e31e987390e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>ccf90a82-0452-469d-8e08-f9af89019236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swipe-out</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1dc3ac5e-7b9b-4193-9aaf-f9f785da0b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>975e2bfa-41be-4158-8503-3bc7d8ff85c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username is required</value>
      <webElementGuid>4fff9274-2524-4444-aaee-8d4e9497ad66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[1]/ol[1]/li[1]</value>
      <webElementGuid>1846ccac-ecb2-4b90-9b93-47fbab23fc48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/ol/li</value>
      <webElementGuid>8e69168e-8429-48e1-b636-c22352ef1038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::li[1]</value>
      <webElementGuid>808d0fbf-d337-4035-b19b-679ec8979c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>f2eabf6a-a96f-4cbc-9810-971166481694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Username is required' or . = 'Username is required')]</value>
      <webElementGuid>55652c65-e4d0-4f93-a9b5-ec9250fc4452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
